### ISSUE TITLE
[FEAT] 질문에 대한 답변 조회

### ISSUE THREAD

**Issue by PgmJun** [Team-Plu/Plu-Server#28]
## Description 📝
질문에 대한 답변을 조회한다.

## To-Do ☑️
- [x] Like 엔티티 구현
- [x] Like 엔티티 ERD 추가
- [x] 질문에 대한 답변 조회 기능 구현
